### ISSUE TITLE
Null pointer dereference upon `cobra -pat`

### ISSUE THREAD

**Issue by myint** [nimble-code/Cobra#2]
Running `cobra -pat` (without any further arguments) results in a null pointer dereference. Probably just due to missing command-line option validation.

https://github.com/nimble-code/Cobra/blob/5c9525b895b78e10b91a404e8e4488d19b75443d/src/cobra_prep.c#L612-L614

```
$ cobra -pat
Segmentation fault: 11
```

With AddressSanitizer compile-time instrumentation enabled:

```
$ cobra -pat
ASAN:DEADLYSIGNAL
=================================================================
==38178==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fffb3941b52 bp 0x7fff57c9be00 sp 0x7fff57c9be00 T0)
==38178==The signal is caused by a READ memory access.
==38178==Hint: address points to the zero page.
    #0 0x7fffb3941b51 in strlen (libsystem_c.dylib:x86_64+0x1b51)
    #1 0x108193817 in wrap_strlen (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x15817)
    #2 0x107f76f68 in pattern cobra_prep.c:614
    #3 0x107f78dfd in main cobra_prep.c:942
    #4 0x7fffb390b234 in start (libdyld.dylib:x86_64+0x5234)
```

**Comment by nimble-code** [comment]
thanks for catching -- fixed
